#! /usr/bin/env python3

spam = ['apples', 'bananas', 'tofu', 'cats']
new_string = spam[0]

for x in range(1, len(spam) - 1):
    new_string = new_string + ', ' + spam[x]
new_string = new_string + ', and ' + spam[x+1]
print(new_string)
