#!/usr/bin/python3

theBoard = {'top-L': ' ', 'top-M': ' ', 'top-R': ' ',
             'mid-L': ' ', 'mid-M': ' ', 'mid-R': ' ' ,
             'low-L': ' ', 'low-M': ' ', 'low-R': ' '}

def printBoard(board):
    print('\n' + board['top-L'] + '|' + board['top-M'] + '|' + board['top-R'])
    print('-+-+-')
    print(board['mid-L'] + '|' + board['mid-M'] + '|' + board['mid-R'])
    print('-+-+-')
    print(board['low-L'] + '|' + board['low-M'] + '|' + board['low-R'] + '\n')

turn = 'X'
# Print valid move choices
print('\nMove selection: \n- top-R \n- top-M \n- top-R \n- mid-L \n- mid-M \n- mid-R \n- low-L \n- low-M \n- low-R\n') 
while True:
    printBoard(theBoard)
    print('Turn for ' + turn + '. Move on which space?')
    move = input()

# Check whether move selection is valid
    if move not in theBoard.keys():
        print('\nInvalid move selection. Please try again')
        print('Move selection: \n- top-R \n- top-M \n- top-R \n- mid-L \n- mid-M \n- mid-R \n- low-L \n- low-M \n- low-R\n')
        continue

# Check whether spot is available
    if theBoard[move] != ' ':
        print('Spot taken, select another move')
        continue
    
    theBoard[move] = turn

# Win Conditions
    if theBoard['top-L'] == 'X' and theBoard['top-M'] == 'X' and theBoard['top-R'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['top-L'] == 'O' and theBoard['top-M'] == 'O' and theBoard['top-R'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['mid-L'] == 'X' and theBoard['mid-M'] == 'X' and theBoard['mid-R'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['mid-L'] == 'O' and theBoard['mid-M'] == 'O' and theBoard['mid-R'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['low-L'] == 'X' and theBoard['low-M'] == 'X' and theBoard['low-R'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['low-L'] == 'O' and theBoard['low-M'] == 'O' and theBoard['low-R'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['top-L'] == 'X' and theBoard['mid-L'] == 'X' and theBoard['low-L'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['top-L'] == 'O' and theBoard['mid-L'] == 'O' and theBoard['low-L'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['top-M'] == 'X' and theBoard['mid-M'] == 'X' and theBoard['low-M'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['top-M'] == 'O' and theBoard['mid-M'] == 'O' and theBoard['low-M'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['top-R'] == 'X' and theBoard['mid-R'] == 'X' and theBoard['low-R'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['top-R'] == 'O' and theBoard['mid-R'] == 'O' and theBoard['low-R'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['top-L'] == 'X' and theBoard['mid-M'] == 'X' and theBoard['low-R'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['top-L'] == 'O' and theBoard['mid-M'] == 'O' and theBoard['low-R'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break
    elif theBoard['top-R'] == 'X' and theBoard['mid-M'] == 'X' and theBoard['low-L'] == 'X':
        printBoard(theBoard)
        print('X has won!')
        break
    elif theBoard['top-R'] == 'O' and theBoard['mid-M'] == 'O' and theBoard['low-L'] == 'O':
        printBoard(theBoard)
        print('O has won!')
        break

# Switch turns
    if turn == 'X':
        turn = 'O'
    else:
        turn = 'X'
