#!/usr/bin/python3

import pyperclip

text = pyperclip.paste()
text_list = text.split('\n')

for n in range(len(text_list)):
    text_list[n] = '* ' + text_list[n]

text = '\n'.join(text_list)
   
pyperclip.copy(text)
