#!/usr/bin/python3

import re
import pyperclip

# Match phone number formatting
phoneRegex = re.compile(r'''(
    (\d{3}|\(\d{3}\))?                # area code
    (\s|-|\.)?                        # separator
    (\d{3})                           # first 3 digits
    (\s|-|\.)                         # separator
    (\d{4})                           # last 4 digits
    (\s*(ext|x|ext.)\s*(\d{2,5}))?    # extension
    )''', re.VERBOSE)

# Match email address formatting
emailRegex = re.compile(r'''(
    [a-zA-Z0-9._%+-]+      # username
    @                      # @ symbol
    [a-zA-Z0-9.-]+         # domain name
    (\.[a-zA-Z]{2,4})      # dot-something
    )''', re.VERBOSE)

# Copy text from clipboard to a string 
textStr = str(pyperclip.paste())

matches = []
# Find phone numbers
for groups in phoneRegex.findall(textStr):
    phoneNum = '-'.join([groups[1], groups[3], groups[5]])
    if groups[8] != '':
        phoneNum += ' x' + groups[8]
    matches.append(phoneNum)

# Find email addresses
for groups in emailRegex.findall(textStr):
    matches.append(groups[0])
    
# If matches found in text, copy to clipboard and print results
if len(matches) > 0:
    pyperclip.copy('\n'.join(matches))
    print('Matches Found: ')
    print('\n'.join(matches))
