#!/usr/bin/python3
# This program tests a password and verifies that it is at least 8 characters long, contains a number, a lowercase and uppercase letter

import re

lowercaseRegex = re.compile(r'\S*[a-z]\S*')
uppercaseRegex = re.compile(r'\S*[A-Z]\S*')
numberRegex = re.compile(r'\S*[0-9]\S*')
lengthRegex = re.compile(r'(.){8,}')

def passwordTest(password):
        if lowercaseRegex.match(password) == None or uppercaseRegex.match(password) == None or numberRegex.match(password) == None or lengthRegex.match(password) == None:
                print('Password not complex, please change password')
